package de.fraunhofer.iosb.svs.spc.db;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import java.util.Set;

@Entity
public class Task {

    @Id
    // not autogenerated but from kb
    private String id;

    @ManyToMany(mappedBy = "tasks")
    @JsonIgnore
    private Set<TargetSystem> usedIn;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Set<TargetSystem> getUsedIn() {
        return usedIn;
    }

    public void setUsedIn(Set<TargetSystem> usedIn) {
        this.usedIn = usedIn;
    }
}
